
function rb_dot_surf_setscale(brain,locs,wts,lcm)

ctmr_gauss_plot(brain,[0 0 0],0)
if exist('lcm')~=1, lcm=max(abs(wts)); end
% % add whether stim - circles - black
% stim_locs=locs(stimsites,:);
% 
% for k=1:size(stim_locs,1)
%     hold on, plot3(stim_locs(k,1)-20,stim_locs(k,2),stim_locs(k,3),'.',...
%         'MarkerSize',30*wts(stimsites(k))/lcm+25,...
%         'Color','k')
% end
% 
% % add positive stim - circles - bars - green -- stimpairs in N x 2 arrangement
% for k=1:size(ecssites,1)
%     %lines between paired electrodes
%     plot3(locs(ecssites(k,:),1)-20,locs(ecssites(k,:),2),locs(ecssites(k,:),3),...
%         'LineWidth',3,...
%         'Color','g')
%     hold on, plot3(locs(ecssites(k,1),1)-20,locs(ecssites(k,1),2),locs(ecssites(k,1),3),'.',...
%         'MarkerSize',30*wts(ecssites(k,1))/lcm+26,...
%         'Color','g')
%     hold on, plot3(locs(ecssites(k,2),1)-20,locs(ecssites(k,2),2),locs(ecssites(k,2),3),'.',...
%         'MarkerSize',30*wts(ecssites(k,2))/lcm+26,...
%         'Color','g')    
% end

% add activity colorscale
for k=1:size(locs,1)
    if abs(wts(k))<(.1*lcm)
        hold on, plot3(locs(k,1),locs(k,2),locs(k,3),'.',...
        'MarkerSize',20,...
        'Color',.35*[1 1 1])        
    elseif wts(k)>=(.1*lcm)
        hold on, plot3(locs(k,1),locs(k,2),locs(k,3),'.',...
        'MarkerSize',30*abs(wts(k))/lcm+20,...
        'Color',.99*[1 1-wts(k)/lcm 1-wts(k)/lcm])
    elseif wts(k)<=(-.1*lcm)
        hold on, plot3(locs(k,1),locs(k,2),locs(k,3),'.',...
        'MarkerSize',30*abs(wts(k))/lcm+20,...
        'Color',.99*[1+wts(k)/lcm 1+wts(k)/lcm 1])
    end
end
