function argout=geostd(argin)
%function argout=geostd(argin)
%calculate the geometric standard deviation of 'argin'
%http://en.wikipedia.org/wiki/Geometric_standard_deviation
%kjm 10/07


argout=exp(...
    (...%start square root
    sum(...
    (...%start sum of squared
    log(abs(argin))-log(geomean(abs(argin)))...
    ).^2 ...
    )...%end sum
    /(length(argin)-1)...
    ).^.5...
    );%end exponent, end equation
